/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'daemontus' at '2/15/17 11:46 AM' with Gradle 3.2.1
 *
 * @author daemontus, @date 2/15/17 11:46 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
